---
- name: Wait for all hosts
  hosts: bastion
  serial: '{{ serial|default("0") }}'
  gather_facts: false
  tasks:
    - name: facts
      set_fact:
        ansible_connection_is_local: '{{ lookup("env","ANSIBLE_CONNECTION")| default(local) }}'

    - name: checking for port open
      wait_for:
        port: 22
        host: "{{ item }}"
        search_regex: OpenSSH
        timeout: 5
      delegate_to: localhost
      with_items: "{{ groups['all'] }}"
      register: port_check
      until: port_check|success
      delay: 1  # Check every 1 seconds. Adjust as you like.
      retries: 120  # Retry up to 120 times. Adjust as needed.
      failed_when: port_check | failed
      when: ansible_connection_is_local != "local"

- name: Gather facts for all hosts
  hosts: all
  serial: '{{ serial|default("0") }}'
  gather_facts: false
  tasks:
    - name: collect facts
      setup:
  tags: always

- name: Log into private registry and force re-authorization
  hosts: all:!bastion
  serial: '{{ serial|default("0") }}'
  gather_facts: false
  become: yes
  tasks:
    - name: Log into private registry and force re-authorization
      docker_login:
        registry: "{{ registry_url }}"
        username: "{{ registry_username }}"
        password: "{{ registry_password }}"
        reauthorize: yes

- name: Apply role ci-tool-stack
  gather_facts: false
  hosts:
    - ci-tool-stack
  serial: '{{ serial|default("0") }}'
  become: yes
  roles:
    - role: ci-tool-stack
      when: enable_ci_tool_stack | bool

    - role: systemd-service
      systemd_service: "{{ {} | combine (ci_tool_stack_systemd_service) }}"
      when: enable_ci_tool_stack | bool

- name: Apply role elk
  gather_facts: false
  hosts:
    - elk
  serial: '{{ serial|default("0") }}'
  become: yes
  roles:
    - role: ci-tool-stack
      ci_tool_stack_conf_dir: "{{ ci_elk_stack_conf_dir }}"
      ci_tool_stack_docker_compose: "{{ ci_elk_stack_docker_compose }}"
      ci_tool_stack_services: "{{ {} | combine (ci_elk_stack_services) }}"
      ci_tool_stack_service_volume_dir : "{{ ci_elk_stack_service_volume_dir }}"
      ci_tool_stack_config_env : "{{ ci_elk_stack_config_env }}"
      when: enable_ci_elk_stack | bool

    - role: systemd-service
      systemd_service: "{{ {} | combine (ci_elk_stack_systemd_service) }}"
      when: enable_ci_elk_stack | bool

- name: Apply role gitlab
  gather_facts: false
  hosts:
    - gitlab
  serial: '{{ serial|default("0") }}'
  become: yes
  roles:
    - role: ci-tool-stack
      ci_tool_stack_conf_dir: "{{ ci_gitlab_stack_conf_dir }}"
      ci_tool_stack_docker_compose: "{{ ci_gitlab_stack_docker_compose }}"
      ci_tool_stack_services: "{{ {} | combine (ci_gitlab_stack_services) }}"
      ci_tool_stack_service_volume_dir : "{{ ci_gitlab_stack_service_volume_dir }}"
      ci_tool_stack_config_env : "{{ ci_gitlab_stack_config_env }}"
      when: enable_ci_gitlab_stack | bool

    - role: systemd-service
      systemd_service: "{{ {} | combine (ci_gitlab_stack_systemd_service) }}"
      when: enable_ci_gitlab_stack | bool

- name: Apply role gitlab backup
  gather_facts: false
  hosts:
    - gitlab
  serial: '{{ serial|default("0") }}'
  become: yes
  roles:
    - role: ci-tool-stack
      ci_tool_stack_conf_dir: "{{ ci_gitlab_backup_conf_dir }}"
      ci_tool_stack_config_env : "{{ ci_gitlab_backup_config_env }}"
      ci_tool_stack_docker_compose: []
      when: enable_ci_gitlab_stack | bool

    - role: systemd-service
      systemd_service: "{{ {} | combine (ci_gitlab_backup_systemd_service) }}"
      systemd_timer: "{{ {} | combine (ci_gitlab_backup_systemd_timer) }}"
      when: enable_ci_gitlab_stack | bool

- name: Apply role nexus
  gather_facts: false
  hosts:
    - nexus
  serial: '{{ serial|default("0") }}'
  become: yes
  roles:
    - role: ci-tool-stack
      ci_tool_stack_conf_dir: "{{ ci_nexus_stack_conf_dir }}"
      ci_tool_stack_docker_compose: "{{ ci_nexus_stack_docker_compose }}"
      ci_tool_stack_services: "{{ {} | combine (ci_nexus_stack_services) }}"
      ci_tool_stack_service_volume_dir : "{{ ci_nexus_stack_service_volume_dir }}"
      ci_tool_stack_config_env : "{{ ci_nexus_stack_config_env }}"
      when: enable_ci_nexus_stack | bool

    - role: systemd-service
      systemd_service: "{{ {} | combine (ci_nexus_stack_systemd_service) }}"
      when: enable_ci_nexus_stack | bool

- name: Apply role jenkins
  gather_facts: false
  hosts:
    - jenkins
  serial: '{{ serial|default("0") }}'
  become: yes
  roles:
    - role: ci-tool-stack
      ci_tool_stack_conf_dir: "{{ ci_jenkins_stack_conf_dir }}"
      ci_tool_stack_docker_compose: "{{ ci_jenkins_stack_docker_compose }}"
      ci_tool_stack_services: "{{ {} | combine (ci_jenkins_stack_services) }}"
      ci_tool_stack_service_volume_dir : "{{ ci_jenkins_stack_service_volume_dir }}"
      ci_tool_stack_config_env : "{{ ci_jenkins_stack_config_env }}"
      when: enable_ci_jenkins_stack | bool

    - role: systemd-service
      systemd_service: "{{ {} | combine (ci_jenkins_stack_systemd_service) }}"
      when: enable_ci_jenkins_stack | bool

- name: Apply role front
  gather_facts: false
  hosts:
    - front
  serial: '{{ serial|default("0") }}'
  become: yes
  roles:
    - role: ci-tool-stack
      ci_tool_stack_conf_dir: "{{ ci_front_stack_conf_dir }}"
      ci_tool_stack_docker_compose: "{{ ci_front_stack_docker_compose }}"
      ci_tool_stack_services: "{{ {} | combine (ci_front_stack_services) }}"
      ci_tool_stack_service_volume_dir : "{{ ci_front_stack_service_volume_dir }}"
      ci_tool_stack_config_env : "{{ ci_front_stack_config_env }}"
      when: enable_ci_front_stack | bool

    - role: systemd-service
      systemd_service: "{{ {} | combine (ci_front_stack_systemd_service) }}"
      when: enable_ci_front_stack | bool
