---
- name: Ensure needed docker-compose config directory exist
  file:
    path: "{{ item }}"
    owner: "{{ ci_tool_stack_config_owner_user | default ('root')}}"
    group: "{{ ci_tool_stack_config_owner_group| default ('root')}}"
    mode: "0750"
    state: directory
  with_items: "{{ ci_tool_stack_conf_dir }}"

- name: Ensure needed service volume directories exist
  file:
    path: "{{ item.dir }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "0750"
    state: directory
  with_items: "{{ ci_tool_stack_service_volume_dir }}"

- name: Ensure extra conf file for service
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default ('0644') }}"
  with_items: "{{ ci_tool_stack_config_env }}"

- name: Ensure docker-compose file for service is up to date
  copy:
    content: "{{ ci_tool_stack_services |to_nice_yaml}}"
    dest: "{{ item }}"
  with_items: "{{ ci_tool_stack_docker_compose }}"

#- name: Ensure docker-compose for service is up to date
#  template:
#    src: ci-tool-stack/docker-compose.yml
#    dest: "{{ item }}"
#  with_items: "{{ ci_tool_stack_docker_compose }}"
